"""empty message

Revision ID: 0c456c8091de
Revises: f46de1afbb72
Create Date: 2023-02-16 10:20:38.277601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c456c8091de'
down_revision = 'f46de1afbb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_born', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_deceased', sa.Integer(), nullable=True))
        batch_op.drop_column('years')

    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_born', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('year_deceased', sa.Integer(), nullable=True))
        batch_op.drop_column('years')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years', postgresql.INT4RANGE(), autoincrement=False, nullable=True))
        batch_op.drop_column('year_deceased')
        batch_op.drop_column('year_born')

    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years', postgresql.INT4RANGE(), autoincrement=False, nullable=True))
        batch_op.drop_column('year_deceased')
        batch_op.drop_column('year_born')

    # ### end Alembic commands ###
