"""empty message

Revision ID: 7bf15ebc0ce0
Revises: d2cce31a328a
Create Date: 2023-03-01 02:01:14.392061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bf15ebc0ce0'
down_revision = 'd2cce31a328a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=125), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_provider', sa.String(length=64), nullable=False),
    sa.Column('oauth_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('oauth_id')
    )
    op.create_table('performer_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'performer_id')
    )
    op.create_table('performer_nationalities',
    sa.Column('performer_id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.ForeignKeyConstraint(['performer_id'], ['performers.id'], ),
    sa.PrimaryKeyConstraint('performer_id', 'nation_id'),
    sa.UniqueConstraint('performer_id', 'nation_id', name='unique_performer_nationalities')
    )
    op.create_table('composer_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'composer_id')
    )
    op.create_table('composer_nationalities',
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.PrimaryKeyConstraint('composer_id', 'nation_id'),
    sa.UniqueConstraint('composer_id', 'nation_id', name='unique_composer_nationalities')
    )
    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('nationality')

    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('style_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'styles', ['style_id'], ['id'])
        batch_op.drop_column('year')

    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.String(length=1000), nullable=True))
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('nationality')
        batch_op.drop_column('title')

    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dates', sa.String(length=25), nullable=True))
        batch_op.drop_column('years')

    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('released_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('style_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))
        batch_op.drop_constraint('recordings_composer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'styles', ['style_id'], ['id'])
        batch_op.drop_column('composer_id')
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('composer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recordings_composer_id_fkey', 'composers', ['composer_id'], ['id'])
        batch_op.drop_column('image')
        batch_op.drop_column('style_id')
        batch_op.drop_column('released_date')

    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('years', postgresql.INT4RANGE(), autoincrement=False, nullable=True))
        batch_op.drop_column('dates')

    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('bio')

    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('style_id')
        batch_op.drop_column('release_date')
        batch_op.drop_column('image')

    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('bio')

    op.drop_table('composer_nationalities')
    op.drop_table('composer_favorites')
    op.drop_table('performer_nationalities')
    op.drop_table('performer_favorites')
    op.drop_table('users')
    op.drop_table('nations')
    # ### end Alembic commands ###
