"""empty message

Revision ID: b2bb1ee48533
Revises: dd427489769e
Create Date: 2023-02-15 12:56:24.242873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2bb1ee48533'
down_revision = 'dd427489769e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('composer_contemporaries', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_composer_contemporaries', ['composer_id', 'contemporary_id'])

    with op.batch_alter_table('performer_contemporaries', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_performer_contemporaries', ['performer_id', 'contemporary_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performer_contemporaries', schema=None) as batch_op:
        batch_op.drop_constraint('unique_performer_contemporaries', type_='unique')

    with op.batch_alter_table('composer_contemporaries', schema=None) as batch_op:
        batch_op.drop_constraint('unique_composer_contemporaries', type_='unique')

    # ### end Alembic commands ###
