"""empty message

Revision ID: dd427489769e
Revises: d0de71e842cf
Create Date: 2023-02-15 12:43:21.448889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd427489769e'
down_revision = 'd0de71e842cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performer_contemporaries',
                    sa.Column('performer_id', sa.Integer(), nullable=False),
                    sa.Column('contemporary_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['contemporary_id'], ['performers.id'], ),
                    sa.ForeignKeyConstraint(
                        ['performer_id'], ['performers.id'], ),
                    sa.PrimaryKeyConstraint('performer_id', 'contemporary_id'),
                    sa.UniqueConstraint('performer_id', 'contemporary_id',
                                        name='unique_contemporaries')
                    )
    with op.batch_alter_table('performer_contemporaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performer_contemporaries_contemporary_id'), [
                              'contemporary_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_performer_contemporaries_performer_id'), [
                              'performer_id'], unique=False)

    op.create_table('composer_contemporaries',
                    sa.Column('composer_id', sa.Integer(), nullable=False),
                    sa.Column('contemporary_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['composer_id'], ['composers.id'], ),
                    sa.ForeignKeyConstraint(
                        ['contemporary_id'], ['composers.id'], ),
                    sa.PrimaryKeyConstraint('composer_id', 'contemporary_id')
                    # sa.UniqueConstraint('composer_id', 'contemporary_id', name='unique_contemporaries')
                    )
    with op.batch_alter_table('composer_contemporaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_composer_contemporaries_composer_id'), [
                              'composer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_composer_contemporaries_contemporary_id'), [
                              'contemporary_id'], unique=False)

    with op.batch_alter_table('contemporaries', schema=None) as batch_op:
        batch_op.drop_index('ix_contemporaries_composer_id')
        batch_op.drop_index('ix_contemporaries_contemporary_id')

    op.drop_table('contemporaries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contemporaries',
                    sa.Column('composer_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('contemporary_id', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['composer_id'], ['composers.id'], name='contemporaries_composer_id_fkey'),
                    sa.ForeignKeyConstraint(['contemporary_id'], [
                        'composers.id'], name='contemporaries_contemporary_id_fkey')
                    )
    with op.batch_alter_table('contemporaries', schema=None) as batch_op:
        batch_op.create_index('ix_contemporaries_contemporary_id', [
                              'contemporary_id'], unique=False)
        batch_op.create_index('ix_contemporaries_composer_id', [
                              'composer_id'], unique=False)

    with op.batch_alter_table('composer_contemporaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(
            'ix_composer_contemporaries_contemporary_id'))
        batch_op.drop_index(batch_op.f(
            'ix_composer_contemporaries_composer_id'))

    op.drop_table('composer_contemporaries')
    with op.batch_alter_table('performer_contemporaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f(
            'ix_performer_contemporaries_performer_id'))
        batch_op.drop_index(batch_op.f(
            'ix_performer_contemporaries_contemporary_id'))

    op.drop_table('performer_contemporaries')
    # ### end Alembic commands ###
