"""empty message

Revision ID: eca9ab63684a
Revises: 7bf15ebc0ce0
Create Date: 2023-05-18 09:54:24.927048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eca9ab63684a'
down_revision = '7bf15ebc0ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('performer_nationalities', schema=None) as batch_op:
        batch_op.drop_constraint('unique_performer_nationalities', type_='unique')

    with op.batch_alter_table('composers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))

    with op.batch_alter_table('composer_nationalities', schema=None) as batch_op:
        batch_op.drop_constraint('unique_composer_nationalities', type_='unique')

    # ### end Alembic commands ###
