"""empty message

Revision ID: f46de1afbb72
Revises: b2bb1ee48533
Create Date: 2023-02-15 19:25:00.798662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46de1afbb72'
down_revision = 'b2bb1ee48533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'composers', ['composer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recordings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('composer_id')

    # ### end Alembic commands ###
